package com.Record.Work;

	//Record Creation
    // record reduces boiler plate code like creation of field, constructor, getter and  toString(), equals(), and hashCode() are generated by the Java compiler during compile time. 
	public record AssociateRecord(int id, String name, String designation) {
		
		private static int totalExperience = 0;

	    // Constructor 1 of this class
	    // Compact Constructor
		public AssociateRecord{
			if (id < 100) {
	            throw new IllegalArgumentException(
	                "Employee Id cannot be below 100.");
	        }
	        if (name.length() < 2) {
	            throw new IllegalArgumentException(
	                "name must be 2 characters or more.");
	        }
		} 
		// Constructor 2 of this class
	    // Alternative Constructor
		
		public AssociateRecord(int id, String name)
	    {
	        this(id, name, null);
	    }

	    // Instance methods
	    public void getNamewithDesignation()
	    {
	        if (name == null)
	            System.out.println("Name unfilled");

	        else
	            System.out.println(name()+" "+designation());
	    }

	    // Static methods
	    public static int getTotalExperience()
	    {
	        return ++totalExperience;
	    }
	
		
		
		
	}


